### ISSUE TITLE
Support Windows line ends in level.txt-s

### ISSUE THREAD

**Issue by singalen** [ondras/trw#1]
For my Git at Windows (or whatever text editor anyone uses), I had to change levelmanager.js to look like:

```
var br = data.search(/\r?\n\r?\n/);
...
var map = data.substring(0, br).split(/\r?\n/);
```

**Comment by ondras** [comment]
Okay, please send a pull request...

**Comment by ondras** [comment]
Fixed, thanks to jokeofweek for a patch.
